import {
  Zap,
  ShieldCheck,
  Cloud,
  Headphones,
  Server,
  Database,
  Globe,
  TrendingUp,
  CheckCircle,
  Star,
  Award,
  Users,
  Cpu,
  Lock,
  BarChart2,
  Rocket,
  Shield,
  Settings,
  Mail,
  Phone,
  MapPin,
  ArrowRight,
  Clock,
  Activity,
  HardDrive,
  Wifi,
  Code,
  Package,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  Zap,
  ShieldCheck,
  Cloud,
  Headphones,
  Server,
  Database,
  Globe,
  TrendingUp,
  CheckCircle,
  Star,
  Award,
  Users,
  Cpu,
  Lock,
  BarChart2,
  Rocket,
  Shield,
  Settings,
  Mail,
  Phone,
  MapPin,
  ArrowRight,
  Clock,
  Activity,
  HardDrive,
  Wifi,
  Code,
  Package,
}

export const iconOptions = [
  { label: 'Zap / Speed', value: 'Zap' },
  { label: 'Shield Check', value: 'ShieldCheck' },
  { label: 'Cloud', value: 'Cloud' },
  { label: 'Headphones / Support', value: 'Headphones' },
  { label: 'Server', value: 'Server' },
  { label: 'Database', value: 'Database' },
  { label: 'Globe / Global', value: 'Globe' },
  { label: 'Trending Up', value: 'TrendingUp' },
  { label: 'Check Circle', value: 'CheckCircle' },
  { label: 'Star', value: 'Star' },
  { label: 'Award', value: 'Award' },
  { label: 'Users / Team', value: 'Users' },
  { label: 'CPU', value: 'Cpu' },
  { label: 'Lock / Security', value: 'Lock' },
  { label: 'Bar Chart', value: 'BarChart2' },
  { label: 'Rocket / Launch', value: 'Rocket' },
  { label: 'Shield', value: 'Shield' },
  { label: 'Settings / Config', value: 'Settings' },
  { label: 'Mail', value: 'Mail' },
  { label: 'Phone', value: 'Phone' },
  { label: 'Map Pin / Location', value: 'MapPin' },
  { label: 'Arrow Right', value: 'ArrowRight' },
  { label: 'Clock / Time', value: 'Clock' },
  { label: 'Activity / Monitor', value: 'Activity' },
  { label: 'Hard Drive', value: 'HardDrive' },
  { label: 'Wifi', value: 'Wifi' },
  { label: 'Code', value: 'Code' },
  { label: 'Package', value: 'Package' },
]
